
from enum import Enum
from typing import Optional

from pydantic import BaseModel
from .llm_provider import BaseLLM, LLMResponse
from mcp_services.mcp_server.mcp_web_search_server import MCPWebSearchServer, SearchResult
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

class LLMTask(BaseModel):
    task_id: str
    description: str
    prompt: str
    system_prompt: Optional[str] = None
    requires_search: bool = False
    requires_search_query_refinement: bool = False
    requires_search_result_refinement: bool = False

class LLMRole(Enum):
    QUERY_REFINER = "query_refiner"
    RESEARCHER = "researcher"
    ANALYZER = "analyzer"
    SYNTHESIZER = "synthesizer"
    VALIDATOR = "validator"


def _get_system_prompts():
    return {
        LLMRole.QUERY_REFINER: """You are an expert medical search query optimizer. Your goal is to transform user questions into precise and effective search queries for medical research.
        Focus on using accurate medical terminology, adding relevant keywords, and formulating it for direct search result relevance (e.g., symptoms, treatments, drug info, disease mechanisms).
        The output should be only the refined query string, with no additional text or explanation. Do not include any conversational phrases or disclaimers.
        """,
        LLMRole.RESEARCHER: """You are a medical research agent. Your role is to:
        1. Analyze medical questions and identify key search terms
        2. Review search results and extract relevant medical information
        3. Focus on evidence-based information from reputable sources
        4. Always mention that medical information should be verified with healthcare professionals
        5. Be precise and factual in your analysis""",

        LLMRole.ANALYZER: """You are a medical analysis agent. Your role is to:
        1. Analyze medical information for accuracy and completeness
        2. Identify potential gaps or inconsistencies in information
        3. Cross-reference information from multiple sources
        4. Assess the reliability of sources and information quality
        5. Highlight any conflicting information found""",

        LLMRole.SYNTHESIZER: """You are a medical synthesis agent. Your role is to:
        1. Combine information from multiple sources into coherent responses
        2. Structure medical information clearly and logically
        3. Ensure balanced presentation of different viewpoints
        4. Create comprehensive yet accessible explanations
        5. Always include appropriate medical disclaimers""",

        LLMRole.VALIDATOR: """You are a medical validation agent. Your role is to:
        1. Review final medical responses for accuracy and safety
        2. Ensure appropriate disclaimers are included
        3. Check that responses don't provide specific medical advice
        4. Validate that information is presented responsibly
        5. Flag any potentially harmful or misleading content"""
    }


class MedicalLLMController:
    def __init__(self, role: LLMRole, llm: BaseLLM, mcp_server:  MCPWebSearchServer ):
        self.role = role
        self.llm = llm
        self.mcp_server = mcp_server
        self.system_prompts = _get_system_prompts()

    async def execute_task(self, task: LLMTask, search_context: Optional[str | SearchResult] = None) -> LLMResponse:
        """
        Execute a given task using the specified LLM and MCP server.

        Args:
            task (LLMTask): The task to execute.
            search_context (Optional[str | SearchResult]): Context for the task, such as search results or additional information.

        Returns:
            LLMResponse: The response generated by the LLM.
        """
        search_info = ""
        full_prompt = task.prompt
        if search_context:
            if isinstance(search_context, SearchResult):
                search_info = f"\n\nSearch Results Context:\nTool: {search_context.tool}\nQuery: {search_context.query}\nAnswer: {search_context.answer}\nSources: {', '.join(search_context.sources)}\nTotal Results: {search_context.total_results}"
            elif isinstance(search_context, str):
                search_info = f"\n\nSearch Results Context:\n{search_context}"
            full_prompt += search_info

            # Get system prompt for this role
        system_prompt = task.system_prompt or self.system_prompts.get(self.role, "")

        # Generate response using the LLM
        response = self.llm.generate_response(full_prompt, system_prompt)

        logger.info(f"Agent {self.role.value} ({self.llm.get_provider().value}) completed task: {task.task_id}")

        return response